// Role-appropriate funny greetings for staff members.
// Shown when a staff user opens /account or /admin instead of the
// generic "Welcome back" line. Picked at random per page load so the
// greeting rotates without any persistence.

export type GreetingRole = "admin" | "coach" | "doctor" | "nurse" | "psychologist";

const ADMIN_GREETINGS = [
  "Wazzup boss man",
  "The captain has boarded",
  "Look who's signed the cheques today",
  "CEO mode: engaged",
  "Rule the empire, one click at a time",
  "Permission slip: self-signed",
  "The keymaster has arrived",
  "Dashboards assemble",
  "Root access, royal entrance",
  "Admin in the building",
  "The algorithm bows before you",
  "Supreme leader, your stats await",
  "Productivity levels: suspiciously high",
  "All hail the console",
  "Hope you had your coffee — numbers incoming",
  "The buck stops here (and also starts here)",
  "Clearance level: everything",
  "The big cheese has logged in",
  "Spreadsheets tremble in your presence",
  "Audit trail: yours truly",
  "One does not simply log in as admin… but here we are",
  "The throne is warm, the KPIs are warmer",
  "Welcome back, commander",
  "Another day, another dashboard",
  "Final boss detected",
  "Ready to move mountains (or just line items)",
  "Authorisation: you",
  "Your kingdom awaits, your highness",
  "Mr./Ms. Director, sir/ma'am",
  "Steering the ship since login",
  "Manager of chaos, reporting for duty",
  "Architect of the org chart",
  "The org chart starts with you",
  "You signed the TOS AND wrote it",
  "All roads lead to this dashboard",
  "Head honcho, hello again",
  "Ctrl+Alt+Defeat: not today",
  "Empire state of mind",
  "Lead the way, leader",
  "Welcome, overseer of the realm",
  "Your benevolent dictatorship continues",
  "Power levels: 9000+",
  "The final say has entered the chat",
  "Big decisions, bigger vibes",
  "The calendar bends to your will",
  "Meetings happen because you blessed them",
  "Your stapler is safe with us",
  "CEO energy radiating",
  "You're the reason the servers are still up",
  "Hello, decision-maker-in-chief",
];

const COACH_GREETINGS = [
  "Let's get people moving, coach",
  "The motivator has entered the chat",
  "Time to turn goals into habits",
  "Your pep talk armoury is fully loaded",
  "Hydration checked? Good — now let's coach",
  "Clipboard up, whistle ready",
  "The habit whisperer is in",
  "Another day, another PR",
  "Lace up — the clients need you",
  "Coach mode: activated",
  "Progress not perfection, you know the drill",
  "You're the reason somebody hit their step goal today",
  "Small wins, big cheers",
  "Your motivational speech hall-of-fame grows",
  "Let's move the needle",
  "Accountability partner has arrived",
  "The habit loop bends toward you",
  "Warm-up done, time to work",
  "High-five energy: maximum",
  "Your pep talks write themselves",
  "Set the reps, track the reps, celebrate the reps",
  "Great coaches change lives — and today is a great day",
  "Streaks don't break on your watch",
  "You turn 'I can't' into 'I did'",
  "Drop and give me… a really supportive message",
  "Form check, vibe check, heart-rate check",
  "The quiet architect of somebody's comeback",
  "Check-in season, and you're the reason",
  "Today's goal: make someone proud of themselves",
  "Nudging humans toward better, one message at a time",
  "Coach, the clients are buffering — go pep them up",
  "The encouragement generator is online",
  "Every rep counts — including this login",
  "You're the friendly voice in their head",
  "Motivation factory now open",
  "Good morning, habit architect",
  "Accountability served warm today",
  "Another day of professionally believing in people",
  "You're literally on the 'before/after' story",
  "Goal crushing, habit building, coach-ing",
  "The cheerleader-with-a-plan has arrived",
  "You make behaviour change look easy",
  "Somebody out there is about to hit a milestone — thanks to you",
  "Time to coach like nobody's watching",
  "Building better humans, one check-in at a time",
  "The streak-saver is online",
  "Welcome back, Captain Consistency",
  "Today's vibe: patient persistence",
  "Here to remind people they've got this",
  "Whistle not required — your energy does the job",
];

const DOCTOR_GREETINGS = [
  "Morning, Doc",
  "The stethoscope has returned",
  "Dr. House would be jealous",
  "Charts cleared, coffee ready",
  "Welcome back, healer",
  "Evidence-based and ready to go",
  "Another day of saving the day (quietly)",
  "The prescription pad is warm",
  "Differential diagnoses, engage",
  "Pulse: steady. Coffee: strong.",
  "The clinician is in",
  "White coat energy, no white coat required",
  "MD mode: on",
  "Your waiting room awaits",
  "Bedside manner, five-star rated",
  "Lab values aligning in your favour",
  "Rounds, rounds, rounds",
  "Hello, healer of humans",
  "The miracle-worker has clocked in",
  "Cortisol is down, the doctor is in",
  "Keep calm and diagnose on",
  "Let's turn numbers into care",
  "Dr. Awesome, reporting for duty",
  "Your pen is mightier than the illness",
  "Back to the clinic cockpit",
  "Welcome, custodian of the evidence",
  "May your notes be concise and your coffee strong",
  "The quiet art of medicine begins again",
  "Your patients are lucky — but they know it",
  "Checking vitals, checking you in",
  "Doctor on deck",
  "The health detective has arrived",
  "Charts, coffee, chaos — the usual",
  "ECGs, ECGs, ECGs… actually, not today, welcome",
  "Your calm bedside manner is a superpower",
  "Nice to see you, medicine maestro",
  "Hippocrates would approve",
  "The differentials are strong today",
  "Back in the lab coat (metaphorically, at least)",
  "Your patients just got a little luckier",
  "The pager is silent — rejoice",
  "Welcome, Doctor Google-Slayer",
  "Another day, another perfectly-written SOAP note",
  "Diagnostic brain: online",
  "Your waiting list appreciates you",
  "Empathy engine: fully charged",
  "Knowledge: encyclopaedic. Patience: saintly.",
  "The consult is now in session",
  "Ready to decode the human body, one case at a time",
  "Scalpel not needed — wisdom required",
];

const NURSE_GREETINGS = [
  "The real MVP has arrived",
  "Nurse on duty, everything is fine now",
  "Scrubs mode: engaged",
  "The calm centre of the storm just logged in",
  "Compassion reporting for duty",
  "IV lines and inner steel — welcome",
  "You're the glue that holds the clinic together",
  "Nurses: the quiet superheroes",
  "Another shift, another life touched",
  "Welcome, patience personified",
  "The tape, the tourniquet, the truth-teller",
  "Vitals vigilante — you've arrived",
  "Hello, heart of the ward",
  "The stethoscope whisperer is back",
  "Everyone breathes easier when you're here",
  "You take notes and also take names",
  "The multitasker-in-chief is online",
  "The chart, the cart, the charm",
  "Welcome back, kindness with a clipboard",
  "You've saved 17 lives before breakfast, probably",
  "Calm in chaos, you made it",
  "Scrubs are a lifestyle, not a uniform",
  "The clinic just got its backbone back",
  "The patient whisperer has arrived",
  "You spot the subtle deterioration nobody else sees",
  "Caffeine, compassion, competence — the trifecta",
  "Ready to make the tough stuff feel manageable",
  "Armed with a thermometer and infinite patience",
  "Welcome, keeper of the wound-care closet",
  "The early-warning system has logged in",
  "The swab, the syringe, the saviour",
  "You are the reason patients smile afterwards",
  "Expert in both IV lines and eye-rolls",
  "Welcome, professional hand-holder",
  "The doctors need you more than they admit",
  "Pager silenced, login registered",
  "The magic behind the meds",
  "Welcome back, head of the triage symphony",
  "The calm voice at 3am — we salute you",
  "Ready to turn panic into a plan",
  "Clipboard ready, kindness refilled",
  "Scrubs in, worries out",
  "The clinician's clinician",
  "Fluency in four things: medicine, empathy, multitasking, chaos",
  "Your shift just got luckier",
  "Compassion at clinical-grade strength",
  "Every patient's favourite (even the grumpy ones)",
  "Back to making hard days softer",
  "The last line of defence and the first smile they see",
  "Welcome, the one who actually runs this place",
];

const PSYCHOLOGIST_GREETINGS = [
  "How does that make you feel… about logging in?",
  "The mind reader has arrived",
  "Couch: metaphorical. Welcome: real.",
  "Deep thoughts, deeper breaths — let's go",
  "The empath has entered the chat",
  "Active listening: activated",
  "Hello, feelings translator",
  "The safe space just got safer",
  "Ready to sit with the hard stuff",
  "Your notes are richer than most novels",
  "Welcome back, Dr. Insight",
  "Calmly curious, as always",
  "The cognitive gardener is pruning today",
  "Mindfully logging in",
  "Boundaries set, compassion ready",
  "The feelings-whisperer has returned",
  "Unconditional positive regard: loaded",
  "Your thought is our command",
  "The therapy couch has Wi-Fi now",
  "Hello, quiet revolutionary",
  "Radical empathy deployed",
  "Welcome, interpreter of human weather",
  "The reframer-in-chief is online",
  "Empathy fuel tank: full",
  "Deep listening, deep breath, let's begin",
  "The emotional architect has arrived",
  "Ready to sit with what's true",
  "The gentle detective of feelings",
  "You hold space better than anyone",
  "Welcome, the one who holds the thread",
  "Session one: log in",
  "Cognitive reframing powers: activated",
  "The brave-space builder is back",
  "The human mind just got a little more understood",
  "Welcome, chief empathy officer",
  "Stillness, curiosity, care — login registered",
  "The wise ear has tuned in",
  "Notice the breath, notice the dashboard",
  "Good to see you, holder of hard truths",
  "Ready to turn pain into language",
  "Welcome, master of the long pause",
  "The reassuring silence has returned",
  "Inner work, outer calm — you've got both",
  "Today's mantra: you are enough (except also read the notes)",
  "Sage mode: on",
  "Welcome, translator of tears",
  "The quiet anchor in somebody's storm",
  "Compassion isn't a skill, it's your whole vibe",
  "Back to making sense of the senseless",
  "Nice to see you, cartographer of the psyche",
];

const GREETINGS: Record<GreetingRole, string[]> = {
  admin: ADMIN_GREETINGS,
  coach: COACH_GREETINGS,
  doctor: DOCTOR_GREETINGS,
  nurse: NURSE_GREETINGS,
  psychologist: PSYCHOLOGIST_GREETINGS,
};

export function pickStaffGreeting(role: GreetingRole, firstName?: string | null): string {
  const pool = GREETINGS[role] || GREETINGS.coach;
  const line = pool[Math.floor(Math.random() * pool.length)];
  if (!firstName) return line;
  const first = firstName.trim().split(/\s+/)[0];
  return first ? `${line}, ${first}` : line;
}
