-- Seed rows for session_library. Schema migration is in
-- migration-program-composer-v1.sql; this file is the seed isolated
-- so it can be pasted independently. Each JSON literal is wrapped
-- in REPLACE(..., E'\r', '') so clipboard CRLF artifacts get
-- stripped before the cast to jsonb (paste-safe from any editor).

INSERT INTO session_library (key, category, modality, level, name, description, duration_min, intensity_rpe, equipment, contraindications, blocks)
VALUES
  ('strength-foundation-fullbody-a', 'exercise', 'strength', 'foundation', 'Foundation Strength A', 'First exposure to compound patterns. Bodyweight or light dumbbell. Builds the movement before adding load.', 35, 5, ARRAY['bodyweight','dumbbells_light'], ARRAY['recent-surgery'], REPLACE('{"warmup_general":[{"name":"Easy walk in place","duration_min":3},{"name":"Cat-cow","duration_min":2}],"warmup_specific":[{"name":"Bodyweight squat","sets":1,"reps":"10"},{"name":"Glute bridge","sets":1,"reps":"10"},{"name":"Wall push-up","sets":1,"reps":"10"}],"main":[{"name":"Goblet squat","sets":3,"reps":"8-10","rest_sec":90,"rpe":6},{"name":"DB Romanian deadlift","sets":3,"reps":"8-10","rest_sec":90,"rpe":6},{"name":"DB bench press (or floor press)","sets":3,"reps":"8-10","rest_sec":90,"rpe":6},{"name":"DB row","sets":3,"reps":"8-10/side","rest_sec":60,"rpe":6}],"finisher":[{"name":"Plank hold","duration_min":1,"description":"3 x 30s, easy pace"}],"cooldown":[{"name":"Box breathing","duration_min":3}]}', E'\r', '')::jsonb),
  ('strength-foundation-fullbody-b', 'exercise', 'strength', 'foundation', 'Foundation Strength B', 'Companion session to A — second compound pattern day.', 35, 5, ARRAY['bodyweight','dumbbells_light'], ARRAY['recent-surgery'], REPLACE('{"warmup_general":[{"name":"Easy walk in place","duration_min":3},{"name":"Worlds greatest stretch","duration_min":2}],"warmup_specific":[{"name":"Reverse lunge","sets":1,"reps":"6/side"},{"name":"Inchworm","sets":1,"reps":"6"}],"main":[{"name":"DB step-up","sets":3,"reps":"8/side","rest_sec":90,"rpe":6},{"name":"DB overhead press (seated)","sets":3,"reps":"8-10","rest_sec":90,"rpe":6},{"name":"Single-arm DB row","sets":3,"reps":"10/side","rest_sec":60,"rpe":6},{"name":"DB suitcase carry","sets":3,"reps":"30s","rest_sec":45,"rpe":6}],"finisher":[{"name":"Dead bug","duration_min":2,"description":"3 x 8/side"}],"cooldown":[{"name":"Hip 90/90 stretch","duration_min":3}]}', E'\r', '')::jsonb),
  ('strength-build-fullbody-a', 'exercise', 'strength', 'build', 'Build Strength A', 'Compound lifts with moderate load. Established movement quality; now building strength.', 50, 7, ARRAY['barbell','dumbbells','bench'], ARRAY['lower-back-injury'], REPLACE('{"warmup_general":[{"name":"Bike or row","duration_min":5}],"warmup_specific":[{"name":"Bodyweight squat to depth","sets":2,"reps":"8"},{"name":"Banded shoulder dislocation","sets":2,"reps":"10"}],"main":[{"name":"Back squat","sets":4,"reps":"5-6","rest_sec":150,"rpe":8},{"name":"Bench press","sets":4,"reps":"5-6","rest_sec":150,"rpe":8},{"name":"Bent-over row","sets":3,"reps":"8","rest_sec":90,"rpe":7}],"finisher":[{"name":"Farmers carry","duration_min":3,"description":"3 x 40m heavy"}]}', E'\r', '')::jsonb),
  ('strength-build-fullbody-b', 'exercise', 'strength', 'build', 'Build Strength B', 'Posterior-chain emphasis. Deadlift + overhead press + accessories.', 50, 7, ARRAY['barbell','dumbbells'], ARRAY['lower-back-injury'], REPLACE('{"warmup_general":[{"name":"Bike or row","duration_min":5}],"warmup_specific":[{"name":"Romanian deadlift drill","sets":2,"reps":"6"},{"name":"Scap pull-up","sets":2,"reps":"5"}],"main":[{"name":"Deadlift","sets":4,"reps":"5","rest_sec":180,"rpe":8},{"name":"Standing overhead press","sets":4,"reps":"5-6","rest_sec":150,"rpe":7},{"name":"Pull-up or lat pulldown","sets":3,"reps":"6-8","rest_sec":90,"rpe":7}],"finisher":[{"name":"Plank","duration_min":3,"description":"3 x 45-60s"}]}', E'\r', '')::jsonb),
  ('strength-performance-lower', 'exercise', 'strength', 'performance', 'Performance Lower Body', 'Heavy compound lower with intensity techniques. For experienced lifters.', 65, 8, ARRAY['barbell','dumbbells','rack'], ARRAY['lower-back-injury','knee-injury'], REPLACE('{"warmup_general":[{"name":"Bike at 70% effort","duration_min":6}],"warmup_specific":[{"name":"Empty-bar squat","sets":2,"reps":"5"},{"name":"Tempo bodyweight squat","sets":2,"reps":"5"}],"main":[{"name":"Back squat","sets":5,"reps":"3-5","rest_sec":180,"rpe":9},{"name":"Front squat","sets":3,"reps":"5","rest_sec":150,"rpe":8},{"name":"Walking lunge","sets":3,"reps":"10/side","rest_sec":90,"rpe":7}],"finisher":[{"name":"Sled push","duration_min":5,"description":"5 x 20m heavy"}]}', E'\r', '')::jsonb),
  ('zone2-foundation-walk', 'exercise', 'zone2', 'foundation', 'Easy Walking Zone 2', 'Steady walking pace where you can hold a conversation. Builds aerobic base.', 30, 3, ARRAY['outdoor','treadmill'], ARRAY[]::text[], REPLACE('{"warmup_general":[{"name":"Slow walk","duration_min":3}],"warmup_specific":[{"name":"Pick up to easy pace","duration_min":2}],"main":[{"name":"Steady walk at conversation pace","duration_min":20,"rpe":4}],"finisher":[{"name":"Slow finish + breathing","duration_min":3}]}', E'\r', '')::jsonb),
  ('zone2-build-cycle', 'exercise', 'zone2', 'build', 'Zone 2 Cycle', 'Steady-state cycling at 65-75% max HR. Conversation pace.', 45, 5, ARRAY['bike','stationary_bike'], ARRAY[]::text[], REPLACE('{"warmup_general":[{"name":"Easy spin","duration_min":5}],"warmup_specific":[{"name":"Pick up to Zone 2 effort","duration_min":3}],"main":[{"name":"Zone 2 steady-state","duration_min":30,"rpe":5}],"finisher":[{"name":"Cool spin","duration_min":5}],"cooldown":[{"name":"Off-bike stretches","duration_min":3}]}', E'\r', '')::jsonb),
  ('zone2-performance-row', 'exercise', 'zone2', 'performance', 'Zone 2 Rowing', 'Longer Z2 row at controlled effort. For trained users building aerobic capacity.', 60, 6, ARRAY['rower'], ARRAY[]::text[], REPLACE('{"warmup_general":[{"name":"Easy row","duration_min":5}],"warmup_specific":[{"name":"Drill pause + reach","duration_min":3}],"main":[{"name":"Z2 steady row","duration_min":45,"rpe":6,"description":"Hold conversation pace; HR <= 75% max"}],"cooldown":[{"name":"Easy spin or walk","duration_min":5}]}', E'\r', '')::jsonb),
  ('hiit-foundation-intervals', 'exercise', 'hiit', 'foundation', 'Walk-Jog Intervals', 'First HIIT — alternating brisk walk + light jog.', 20, 6, ARRAY['outdoor','treadmill'], ARRAY['cardiac-condition'], REPLACE('{"warmup_general":[{"name":"Brisk walk","duration_min":5}],"warmup_specific":[{"name":"2 x 30s easy jog","duration_min":2}],"main":[{"name":"Walk-jog intervals","duration_min":10,"description":"30s jog / 90s walk x 5","rpe":7}],"cooldown":[{"name":"Walk","duration_min":3}]}', E'\r', '')::jsonb),
  ('hiit-build-circuit', 'exercise', 'hiit', 'build', 'Bodyweight Circuit', '6 movements, 30 work / 30 rest, 3 rounds.', 25, 8, ARRAY['bodyweight'], ARRAY['knee-injury','shoulder-injury'], REPLACE('{"warmup_general":[{"name":"Jumping jacks","duration_min":3}],"warmup_specific":[{"name":"Bodyweight squat","sets":1,"reps":"10"},{"name":"Push-up","sets":1,"reps":"5"}],"main":[{"name":"Circuit: squat -> push-up -> lunge -> row -> mountain climber -> plank","duration_min":18,"description":"30s on / 30s off x 6 moves x 3 rounds","rpe":8}],"cooldown":[{"name":"Slow walk + box breathing","duration_min":4}]}', E'\r', '')::jsonb),
  ('hiit-performance-tabata', 'exercise', 'hiit', 'performance', 'Tabata Sprints', '20s on / 10s off x 8 rounds, bike or row.', 30, 9, ARRAY['bike','rower'], ARRAY['cardiac-condition','recent-surgery'], REPLACE('{"warmup_general":[{"name":"Easy spin","duration_min":5}],"warmup_specific":[{"name":"3 x 15s accel","duration_min":3}],"main":[{"name":"Tabata: 20s max / 10s rest x 8","duration_min":4,"rpe":10},{"name":"Recover","duration_min":4,"rpe":3},{"name":"Second Tabata block","duration_min":4,"rpe":10}],"cooldown":[{"name":"Easy spin","duration_min":5}]}', E'\r', '')::jsonb),
  ('mobility-foundation-flow', 'exercise', 'mobility', 'foundation', 'Daily Mobility Flow', '15-min full-body mobility for desk workers + returning athletes.', 15, 2, ARRAY['bodyweight','mat'], ARRAY[]::text[], REPLACE('{"warmup_general":[{"name":"Cat-cow","duration_min":2}],"warmup_specific":[],"main":[{"name":"Worlds greatest stretch","sets":2,"reps":"5/side"},{"name":"90/90 hip switch","sets":2,"reps":"6/side"},{"name":"T-spine windmill","sets":2,"reps":"5/side"},{"name":"Scapular wall slide","sets":2,"reps":"10"}],"finisher":[{"name":"Childs pose hold","duration_min":2}]}', E'\r', '')::jsonb),
  ('mobility-build-yoga', 'exercise', 'mobility', 'build', 'Yoga Flow', '20-min standing flow — strength-builders mobility companion.', 20, 3, ARRAY['mat'], ARRAY[]::text[], REPLACE('{"warmup_general":[{"name":"Down-dog / cobra cycles","duration_min":3}],"main":[{"name":"Sun salutation A","sets":3,"reps":"full flow"},{"name":"Warrior 1-2-3 sequence","sets":2,"reps":"per side"},{"name":"Lizard pose","sets":1,"reps":"60s/side"}],"cooldown":[{"name":"Pigeon + savasana","duration_min":5}]}', E'\r', '')::jsonb),
  ('breathwork-box', 'exercise', 'breathwork', NULL, 'Box Breathing', '4-4-4-4 breath pattern. Sympathetic-to-parasympathetic shift.', 5, 1, ARRAY[]::text[], ARRAY[]::text[], NULL),
  ('breathwork-physiological-sigh', 'exercise', 'breathwork', NULL, 'Physiological Sigh', 'Two short inhales through the nose, one long exhale through the mouth. Fastest known down-regulation.', 3, 1, ARRAY[]::text[], ARRAY[]::text[], NULL),
  ('meditation-foundation-10min', 'mental', 'meditation', 'foundation', '10-min Body Scan', 'Guided body-scan meditation. Entry-point for mindfulness practice.', 10, 1, ARRAY[]::text[], ARRAY[]::text[], NULL),
  ('meditation-build-20min', 'mental', 'meditation', 'build', '20-min Open Awareness', 'Open-awareness meditation. For users with an established practice.', 20, 1, ARRAY[]::text[], ARRAY[]::text[], NULL)
ON CONFLICT (key) DO NOTHING;
