// ============================================================================
// The "standard" Lifeline employee-introduction deck, expressed as data.
// This is the seed content cloned by both built-in templates (see
// templates.ts). Images point at existing /public assets so a fresh
// presentation looks complete before anything is uploaded.
// ============================================================================
import type { Slide } from "./types";

const IMG = {
  hero: "/presentation-images/eyjar-running.png",
  closing: "/presentation-images/banner.png",
  clinic: "/presentation-images/victor-clinic-bw.jpg",
  victor: "/team/victor.png",
  mads: "/team/mads.png",
  vignir: "/team/vignir.png",
  dagbjort: "/team/dagbjort.png",
  appHealth: "/app-screenshot-health.jpg",
  appReport: "/app-screenshot-report.jpg",
  appCommunity: "/app-screenshot-community.jpg",
  appMeasurements: "/app-screenshot-measurements.jpg",
  appCoach: "/app-screenshot-coach.jpg",
};

export function standardDeckSlides(): Slide[] {
  return [
    {
      id: "s1", type: "title", theme: "dark", bg: IMG.hero,
      kicker: "Welcome",
      heading: "Your health,\n==starting today.==",
      lead: "A 30-minute introduction to Lifeline — the health benefit your workplace is giving you, and what it can do for the next ten years of your life.",
      tagline: "Ahead of yourself.",
      notes: "Welcome them warmly. This is a benefit their company chose to give them — frame it as an investment in them, not an obligation. ~30 minutes, questions welcome at the end.",
    },
    {
      id: "s2", type: "stats", theme: "light",
      kicker: "Why this matters",
      heading: "Our healthcare is brilliant at ==treatment.== It does almost nothing for ==prevention.==",
      lead: "By the time most of us see a doctor, something is already wrong. The years before that — the habits that decide whether we ever get there — are left entirely to us.",
      stats: [
        { value: "59%", label: "of Icelanders are overweight or obese — the highest rate in Europe." },
        { value: "#1", label: "cause of early death worldwide: lifestyle, not accidents or infection." },
        { value: "80%", label: "of chronic disease is considered preventable through daily habits." },
        { value: "0", label: "homegrown tools in Iceland that turn your real health data into a plan — until now." },
      ],
      footnote: "Sources: Icelandic public-health statistics & WHO non-communicable-disease estimates. Figures are illustrative for this talk.",
      notes: "Land the gap: medicine is reactive. The decade before illness is unmanaged. Make it personal — most people here know someone affected. Don't fear-monger; set up the opportunity.",
    },
    {
      id: "s3", type: "cards", theme: "dark", columns: 3,
      kicker: "What Lifeline is",
      heading: "The missing layer between the healthcare system and your daily life.",
      cards: [
        { icon: "clip", title: "A real assessment", body: "Clinical-grade health check — blood work, body composition and lifestyle — reviewed by a physician." },
        { icon: "target", title: "A personal plan", body: "From your actual results, a plan built for your body across four pillars of health." },
        { icon: "pulse", title: "Daily action", body: "Small, specific things to do each day — that adapt as you improve and keep you on track." },
      ],
      lead: "Not another step-counter. Active coaching, grounded in your clinical data.",
      notes: "The one-sentence definition: the layer between the healthcare system and daily life. Stress 'grounded in YOUR clinical data' — that's the differentiator vs every step-counter.",
    },
    {
      id: "s4", type: "quote", theme: "light",
      kicker: "Our purpose",
      quote: "We exist to create ==real, lasting change== in people's health — not more information, but a plan that actually happens.",
      lead: "You already know you should move more, eat better and sleep enough. Knowing was never the problem. Lifeline turns knowing into doing — one day at a time.",
      notes: "Slow down here. This is the emotional core: knowing was never the problem. Everyone in the room already 'knows' — Lifeline is about doing.",
    },
    {
      id: "s5", type: "story", theme: "dark",
      kicker: "Our story",
      heading: "Born on the clinic floor.",
      lead: "Lifeline began with a frustration two doctors — Victor Guðmundsson and Mads Christian Aanesen — couldn't shake: they kept meeting patients who arrived too late, for problems years of small choices could have prevented.",
      bullets: [
        "Born medical. Founded and reviewed by doctors — credibility without the cold clinic feel.",
        "Born in Iceland. Made for our healthcare context, our language and our culture.",
        "One mission. Make prevention as serious, and as supported, as treatment.",
      ],
      photo: IMG.clinic,
      caption: "From the clinic floor to a nationwide preventive-health platform.",
      notes: "Tell the founding story in your own words — a real patient who came too late lands harder than statistics. The b&w clinic photo sets the tone: this started with doctors, not a startup pitch.",
    },
    {
      id: "s6", type: "team", theme: "light",
      kicker: "The team",
      heading: "How we became this team.",
      lead: "Physicians at the core — surrounded by health coaches, clinic nurses and engineers, all working from the same clinical foundation.",
      members: [
        { photo: IMG.victor, flag: "Co-founder", name: "Victor Guðmundsson", role: "CEO · Medical Doctor & Coach" },
        { photo: IMG.mads, flag: "Co-founder", name: "Mads C. Aanesen", role: "CTO · Medical Doctor & Coach" },
        { photo: IMG.vignir, flag: "Advisor", name: "Vignir Sigurðsson", role: "Chief Medical Advisor · Pediatrician" },
        { photo: IMG.dagbjort, flag: "Clinical", name: "Dagbjört Guðbrandsdóttir", role: "Medical Doctor" },
      ],
      footnote: "…plus the health coaches and clinic nurses who run assessments across Iceland. Swap in your own line-up here.",
      notes: "Introduce the team by name — make it human. Note that physicians sit at the core, but the people employees will actually meet are the coaches and the clinic nurses running their assessment. Swap in your real line-up.",
    },
    {
      id: "s7", type: "pillars", theme: "light",
      kicker: "The model",
      heading: "Four pillars. One connected system.",
      lead: "Most apps fix one thing. Your body doesn't work in silos — sleep affects training, training affects mood, mood affects eating. We treat all four together.",
      pillars: [
        { key: "exercise", icon: "dumbbell", title: "Exercise", body: "Strength, cardio, mobility — matched to your level." },
        { key: "nutrition", icon: "leaf", title: "Nutrition", body: "Sustainable eating, not crash diets." },
        { key: "sleep", icon: "moon", title: "Sleep", body: "The foundation everything else is built on." },
        { key: "mental", icon: "brain", title: "Mental wellness", body: "Stress, resilience and a clearer mind." },
      ],
      notes: "Use a relatable chain: bad sleep → skipped workout → worse food → low mood. That's why four pillars together, not one app each.",
    },
    {
      id: "s8", type: "cards", theme: "dark", columns: 2,
      kicker: "The Health Assessment",
      heading: "See what's actually happening inside your body.",
      lead: "This is where everyone starts. It's the part most health apps skip — and the reason your plan is built on facts, not guesses.",
      cards: [
        { icon: "pulse", title: "Blood panel", body: "50+ markers — cholesterol, blood sugar, inflammation, liver, kidney, thyroid and more." },
        { icon: "chart", title: "Body composition", body: "Body fat, muscle and more — measured properly, not just a number on a scale." },
        { icon: "clip", title: "Lifestyle questionnaire", body: "Sleep, stress, activity, nutrition and history — across all four pillars." },
        { icon: "doc", title: "Physician review", body: "A doctor reads your results and flags anything that matters before your plan begins." },
      ],
      notes: "Slow down. This is what makes Lifeline credible. Reassure the needle-shy: standard blood draw, quick. Emphasise a real physician reviews results.",
    },
    {
      id: "s9", type: "steps", theme: "light",
      kicker: "How the assessment works",
      heading: "Simple, and mostly done for you.",
      steps: [
        { title: "Book", body: "Pick a slot — at a clinic station, or on-site here at your workplace." },
        { title: "Blood test", body: "A quick, standard blood draw. Sent to the lab; results come back into Lifeline." },
        { title: "Body composition", body: "A short, non-invasive measurement of body fat and muscle." },
        { title: "Questionnaire", body: "You complete the lifestyle questions in the app — about 10 minutes." },
        { title: "Physician review", body: "A doctor reviews everything and confirms what's safe and where to focus." },
        { title: "Your results", body: "You get your numbers, your Lifestyle Score, and a plan built from them." },
      ],
      notes: "Walk through the six steps as 'mostly done for you.' Mention the on-site option at the workplace if that's arranged. Keep it light and low-effort.",
    },
    {
      id: "s10", type: "phone-feature", theme: "dark",
      kicker: "What you get out of it",
      heading: "Clarity — and a starting line.",
      bullets: [
        "Your real numbers, explained in plain language — no medical jargon.",
        "Your Lifestyle Score (Lífstílseinkunn) — one 0–10 number across all four pillars, that you can watch move.",
        "A personalised plan calibrated to your results, your fitness level and your goals.",
        "Peace of mind — a physician has looked at your health and flagged anything worth knowing.",
      ],
      phone: IMG.appHealth,
      notes: "Show the score. The Lifestyle Score is the one number to rally around. Mention peace of mind — a doctor has looked at their health.",
    },
    {
      id: "s11", type: "cards", theme: "light", columns: 4,
      kicker: "Why this actually sticks",
      heading: "Knowing isn't enough. Doing — with support — is.",
      cards: [
        { icon: "target", title: "Small daily wins", body: "3–5 specific actions a day. Achievable beats overwhelming, every time." },
        { icon: "spark", title: "Streaks & progress", body: "Watch your numbers move and your streak grow. Momentum is motivating." },
        { icon: "users", title: "Community", body: "Friends, challenges and leaderboards. People who show up together, stay." },
        { icon: "pulse", title: "A coach in your corner", body: "Real guidance when you're stuck — not just a chart that judges you." },
      ],
      lead: "~65% more likely to reach your goals with an accountability partner. Lifeline builds that in.",
      notes: "The behaviour-change slide. Emphasise small daily wins over heroic overhauls. The 65% stat is illustrative — present as 'research consistently shows.'",
    },
    {
      id: "s12", type: "bullets", theme: "dark",
      kicker: "Privacy & security",
      heading: "Your data stays yours.",
      lead: "Health data is the most personal data there is. We treat it that way — and your employer never sees your individual results.",
      chips: [ { label: "GDPR-compliant" }, { label: "Encrypted" }, { label: "Clinically governed" } ],
      bullets: [
        "Your employer never sees your numbers. They fund the benefit; they only ever see anonymous, aggregate participation — never an individual's results.",
        "You control access. You choose what the app reads from your phone or wearable, and can revoke it any time.",
        "Only your care team can see your health data — under clinical confidentiality, the same as any medical record.",
        "Built in Europe, under European rules. Data protection isn't an afterthought — it's a starting requirement.",
      ],
      notes: "Most important slide for trust. Say it plainly and twice: the employer never sees individual results. Pause for it to land — this unlocks honest participation.",
    },
    {
      id: "s13", type: "bullets", theme: "light",
      kicker: "After the assessment",
      heading: "This is where the change happens.",
      lead: "The assessment is the starting line, not the finish. From your results, Lifeline builds structured programs — and turns them into something you do every day.",
      bullets: [
        "Structured 4–12 week programs in each pillar, matched to your level and goals.",
        "A daily action plan that tells you exactly what to do — morning, midday, evening.",
        "It adapts as you go — easier on a tired week, harder as you get stronger.",
        "Visible progress — watch your Lifestyle Score and your real markers move over time.",
      ],
      notes: "The assessment is a starting line. The programs + daily plan are where health actually changes. Adapts to real life (tired weeks, travel).",
    },
    {
      id: "s14", type: "app-showcase", theme: "dark",
      kicker: "The Lifeline app",
      heading: "Everything in your pocket — coaching, accountability and community.",
      tag: "Coming soon",
      phones: [ IMG.appReport, IMG.appCommunity, IMG.appMeasurements ],
      bullets: [
        "Today — your daily actions, organised by time of day.",
        "My Health — Lifestyle Score, biomarkers & body-composition trends.",
        "Health Coach — programs, video lessons and quizzes across all four pillars.",
        "Wearables — Apple Health & Android sync steps, heart rate, HRV and sleep automatically.",
        "Community — friends, events, challenges, leaderboards and streaks.",
        "Wellness Pulse — a quick monthly check-in that refreshes your plan.",
      ],
      notes: "Demo the app if you can. It's 'coming soon' — set expectations on timing. Pull the live feature names so it feels real.",
    },
    {
      id: "s15", type: "coaching", theme: "light",
      kicker: "Coaching",
      heading: "Smart guidance, and real humans.",
      lead: "An AI coach handles the day-to-day — suggesting actions and content from your data. A human coach is there for the things that matter.",
      phone: IMG.appCoach,
      cards: [
        { icon: "spark", title: "AI coach — always on", body: "Personalised recommendations and the right next action, every day, for everyone." },
        { icon: "users", title: "Personal coach — message anytime", body: "A real coach who can review your data, adjust your programs and answer your questions." },
        { icon: "cal", title: "Video consultations", body: "Book a call to review progress and tune your plan to where you are now." },
      ],
      notes: "Clarify AI handles daily nudges; humans handle the meaningful moments. Note coach access depends on plan/tier if relevant to your rollout.",
    },
    {
      id: "s16", type: "bullets", theme: "dark", tag: "Optional",
      kicker: "Every three months",
      heading: "The quarterly doctor interview.",
      lead: "Optional, but powerful. Four times a year, you can sit down with a doctor — by video — to look at the bigger picture.",
      bullets: [
        "Review the trend, not just a snapshot — how your markers and habits are moving.",
        "Ask anything — a real physician, with your data in front of them.",
        "Adjust the plan — set the focus for the next quarter.",
        "Catch things early — the whole point of prevention.",
      ],
      footnote: "Entirely your choice — opt in when it's useful to you.",
      notes: "Emphasise OPTIONAL. Some will love the quarterly doctor call; others won't use it. Frame as catching things early — the essence of prevention.",
    },
    {
      id: "s17", type: "timeline", theme: "light",
      kicker: "Your journey",
      heading: "From one assessment to a healthier decade.",
      nodes: [
        { icon: "clip", title: "Assessment", body: "Know where you stand today." },
        { icon: "target", title: "Your plan", body: "Built from your real results." },
        { icon: "pulse", title: "Daily action", body: "Small wins, with support." },
        { icon: "doc", title: "Quarterly review", body: "Optional doctor check-in." },
        { icon: "chart", title: "Reassess", body: "See how far you've come." },
      ],
      lead: "It's a loop, not a one-off. Each cycle you know more, do more, and feel the difference.",
      notes: "Recap as a repeating loop, not a one-off event. Each cycle compounds.",
    },
    {
      id: "s18", type: "closing", theme: "dark", bg: IMG.closing,
      kicker: "Getting started",
      heading: "The best time was years ago.\nThe next best time is ==today.==",
      lead: "Book your assessment, and we'll take it from there. Questions? Now's the time.",
      tagline: "Ahead of yourself.",
      footnote: "Thank you — over to questions.",
      notes: "Clear call to action: how exactly do they book? Have the link/QR/sign-up ready. Then open the floor for questions.",
    },
  ];
}
